services:
  postgres-db:
    image: postgres:15-alpine
    container_name: smartgate-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: smartgate_db
      POSTGRES_USER: smartgate_user
      POSTGRES_PASSWORD: smartgate_password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    restart: unless-stopped

  db-adminer:
    image: adminer
    container_name: smartgate-adminer
    ports:
      - "8080:8080"
    restart: unless-stopped

  backend-api:
    build:
      context: ./backend
    container_name: smartgate-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/smartgate_db
      SPRING_DATASOURCE_USERNAME: smartgate_user
      SPRING_DATASOURCE_PASSWORD: smartgate_password
      SMARTGATE_INTERCOM_HOST: 192.168.1.100
      SMARTGATE_INTERCOM_PORT: 5432
    depends_on:
      - postgres-db
    restart: unless-stopped
    develop:
      watch:
        - action: rebuild
          path: ./backend/src
        - action: rebuild
          path: ./backend/pom.xml

volumes:
  pgdata:
