spring.application.name=backend


server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/smartgate_db
spring.datasource.username=smartgate_user
spring.datasource.password=smartgate_password

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true